// ==UserScript==
// @name        Privacy Frontend Redirect - Mini
// @match       *://*/*
// @exclude     *://account*/*
// @exclude     *://messages.*/*
// @grant       none
// @version     4.2.7
// @author      NoUser
// @description This script redirects to privacy friendly front-ends of popular services, such as YouTube, Twitter, Reddit, Imgur, Instagram, TikTok, etc. Additionally, it replaces iframes and outgoing links to non frontend services with their privacy-friendly counterparts. The purpose of this script is to protect the user's privacy by avoiding the collection of personal data by these services.
// @run-at      document-start
// @namespace   https://github.com/NyeUsr/Userscripts/raw/main/Privacy%20Frontend%20Redirect.user.js
// @homepage    https://github.com/NyeUsr/Userscripts/
// @license     MIT
// ==/UserScript==

const hostname=window.location.hostname,hosts={"www.youtube.com":["invidious.privacydev.net","vid.puffyan.us","inv.vern.cc","invidious.kavin.rocks","invidious.tiekoetter.com","inv.riverside.rocks","iv.ggtyler.dev","invidious.nerdvpn.de"],"www.youtube-nocookie.com":["invidious.privacydev.net","vid.puffyan.us","inv.vern.cc","invidious.kavin.rocks","invidious.tiekoetter.com","inv.riverside.rocks","iv.ggtyler.dev","invidious.nerdvpn.de"],"m.youtube.com":["invidious.privacydev.net","vid.puffyan.us","inv.vern.cc","invidious.kavin.rocks","invidious.tiekoetter.com","inv.riverside.rocks","iv.ggtyler.dev","invidious.nerdvpn.de"],"twitter.com":["nitter.sneed.network","canada.unofficialbird.com","nitter.privacytools.io","nitter.foss.wtf","nitter.privacy.com.de","nitter.1d4.us","nitter.poast.org","twitter.censors.us"],"mobile.twitter.com":["nitter.sneed.network","canada.unofficialbird.com","nitter.privacytools.io","nitter.foss.wtf","nitter.privacy.com.de","nitter.1d4.us","nitter.poast.org","twitter.censors.us"],"www.reddit.com":["libreddit.eu.org","libreddit.spike.codes","lr.odyssey346.dev","rd.funami.tech","libreddit.dcs0.hu","lr.vern.cc","www.troddit.com"],"imgur.com":["rimgo.pussthecat.org","rimgo.totaldarkness.net","rimgo.vern.cc","imgur.artemislena.eu","rimgo.privacydev.net","rimgo.bus-hit.me"],"i.imgur.com":["rimgo.pussthecat.org","rimgo.totaldarkness.net","rimgo.vern.cc","imgur.artemislena.eu","rimgo.privacydev.net","rimgo.bus-hit.me"],"i.stack.imgur.com":["rimgo.pussthecat.org","rimgo.totaldarkness.net","rimgo.vern.cc","imgur.artemislena.eu","rimgo.privacydev.net","rimgo.bus-hit.me"],"www.instagram.com":["bibliogram.froth.zone","ig.tokhmi.xyz"],"www.tiktok.com":["proxitok.pussthecat.org","tok.habedieeh.re","tok.artemislena.eu","proxitok.privacydev.net"],"www.imdb.com":["ld.vern.cc","libremdb.esmailelbob.xyz","lmdb.tokhmi.xyz","libremdb.iket.me","libremdb.pussthecat.org"],"translate.google.com":["lingva.ml","translate.plausibility.cloud","lingva.lunar.icu","translate.projectsegfau.lt","translate.jae.fi"],"medium.com":["scribe.rip","scribe.nixnet.services","scribe.citizen4.eu","scribe.bus-hit.me","scribe.froth.zone","scribe.rawbit.ninja"]},replaceUrl=e=>{let{host:i}=new URL(e);if(i in hosts){let r=hosts[i];return Array.isArray(r)&&(r=r[Math.floor(Math.random()*r.length)]),e.replace(i,r)}return e};try{let e=hosts[hostname];e&&(window.location.href=replaceUrl(window.location.href))}catch(i){console.error(i.message)}window.addEventListener("load",function(){try{let e=document.querySelectorAll(`iframe[src*="${window.location.host}"]`);e.forEach(e=>{let i=document.createElement("iframe");["src","width","height","frameborder","allowfullscreen","allow","title"].forEach(r=>{e.hasAttribute(r)&&i.setAttribute(r,e.getAttribute(r))}),e.parentNode.replaceChild(i,e)});let i=document.querySelectorAll("a");i.forEach(e=>{let i=e.href,r=replaceUrl(i);r!==i&&(e.href=r)})}catch(r){console.error(r.message)}});
